// <auto-generated />
using System;
using CryptoApi.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CryptoApi.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.6");

            modelBuilder.Entity("CryptoApi.Model.Coins", b =>
                {
                    b.Property<int>("CoinId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagenUrl")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Valor")
                        .HasColumnType("REAL");

                    b.HasKey("CoinId");

                    b.ToTable("Coins");

                    b.HasData(
                        new
                        {
                            CoinId = 1,
                            Descripcion = "Bitcoin",
                            ImagenUrl = "https://cdn.icon-icons.com/icons2/1487/PNG/512/8369-bitcoin_102502.png",
                            Valor = 20916.5
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
